version: '3.8'

services:
  # --- BACKEND ---
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # container_name: saas_api (BORRADO)
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - DB_DATABASE=saas_video
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db
      - redis
    # -------------------------------------------------------
    # ¡BORRA O COMENTA ESTO!
    # volumes:
    #   - ./backend:/var/www/html  <-- ESTO OCULTABA EL VENDOR
    # -------------------------------------------------------
    networks:
      - saas_net

  # --- FRONTEND ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # container_name: saas_frontend (BORRADO)
    ports:
      - "5173:5173"
    # -------------------------------------------------------
    # ¡BORRA O COMENTA ESTO TAMBIÉN!
    # volumes:
    #   - ./frontend:/app         <-- ESTO OCULTABA NODE_MODULES
    #   - /app/node_modules
    # -------------------------------------------------------
    networks:
      - saas_net

  # --- AI WORKER ---
  ai_worker:
    build:
      context: ./ai_engine
      dockerfile: Dockerfile
    # container_name: saas_ai_worker (BORRADO)
    command: python -u src/worker_manager.py
    environment:
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    # -------------------------------------------------------
    # ¡BORRA O COMENTA ESTO!
    # volumes:
    #   - ./ai_engine/src:/app/src  <-- USAMOS EL CÓDIGO DE LA IMAGEN
    #   - ./ai_engine/models:/app/models
    # -------------------------------------------------------
    depends_on:
      - redis
    networks:
      - saas_net

  # --- INFRA (REDIS, DB, LABEL STUDIO) ---
  # Estos SÍ llevan volumen porque guardan datos, no código.
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    networks:
      - saas_net

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: saas_video
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql  # ESTE SÍ SE QUEDA
    networks:
      - saas_net

  label_studio:
    image: heartexlabs/label-studio:latest
    ports:
      - "8081:8080"
    volumes:
      - label_studio_data:/label-studio/data # ESTE SÍ SE QUEDA
    networks:
      - saas_net

networks:
  saas_net:
    driver: bridge

volumes:
  db_data:
  label_studio_data: