version: '3.8'

services:
  # --- BACKEND ---
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # container_name: ELIMINADO
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - DB_DATABASE=saas_video
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db
      - redis
    # -----------------------------------------------------
    # ¡VOLUMES ELIMINADOS! (Esto soluciona el error de vendor)
    # -----------------------------------------------------
    networks:
      - saas_net

  # --- FRONTEND ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # container_name: ELIMINADO
    ports:
      - "5173:5173"
    # -----------------------------------------------------
    # ¡VOLUMES ELIMINADOS! (Esto soluciona el error de node_modules)
    # -----------------------------------------------------
    networks:
      - saas_net

  # --- AI WORKER ---
  ai_worker:
    build:
      context: ./ai_engine
      dockerfile: Dockerfile
    # container_name: ELIMINADO
    command: python -u src/worker_manager.py
    environment:
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    # -----------------------------------------------------
    # ¡VOLUMES ELIMINADOS!
    # -----------------------------------------------------
    depends_on:
      - redis
    networks:
      - saas_net

  # --- INFRAESTRUCTURA (Estos SÍ llevan volúmenes para guardar datos) ---
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    networks:
      - saas_net

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: saas_video
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - saas_net

  label_studio:
    image: heartexlabs/label-studio:latest
    ports:
      - "8081:8080"
    volumes:
      - label_studio_data:/label-studio/data
    networks:
      - saas_net

networks:
  saas_net:
    driver: bridge

volumes:
  db_data:
  label_studio_data: