version: '3.8'

services:
  # --- BACKEND ---
  api:
      build:
        context: ./backend
        dockerfile: Dockerfile
      # container_name: ELIMINADO
      ports:
        - "8000:8000"
      command: 
        - php artisan serve --host=0.0.0.0 --port=8000
      environment:
        - DB_HOST=db
        # ... resto de variables
      depends_on:
        - db
        - redis
      networks:
        - saas_net
      links:        # <--- Agrega esto para reforzar la conexión DNS
        - redis

  # --- FRONTEND ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # container_name: ELIMINADO
    ports:
      - "5173:5173"
    # -----------------------------------------------------
    # ¡VOLUMES ELIMINADOS! (Esto soluciona el error de node_modules)
    # -----------------------------------------------------
    networks:
      - saas_net

  # --- AI WORKER ---
  ai_worker:
      build:
        context: ./ai_engine
        dockerfile: Dockerfile
      # container_name: ELIMINADO
      # CAMBIO: Cambiamos el comando para que corra uvicorn (servidor web)
      command: uvicorn src.worker_manager:app --host 0.0.0.0 --port 5000
      environment:
        - REDIS_HOST=redis
        - PYTHONUNBUFFERED=1
      ports:
        - "5000:5000"  # <--- ¡NUEVO PUERTO PARA VIDEO!
      depends_on:
        - redis
      networks:
        - saas_net

  # --- INFRAESTRUCTURA (Estos SÍ llevan volúmenes para guardar datos) ---
  redis:
      image: redis:alpine
      # container_name: ELIMINADO (Ya lo habíamos quitado, bien)
      ports:
        - "6380:6379"
      networks:
        - saas_net
      # AGREGAR ESTO: Comando para asegurar que escuche en todas las interfaces
      command: redis-server --bind 0.0.0.0
  # --- BASE DE DATOS ---
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: saas_video
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - saas_net

  label_studio:
    image: heartexlabs/label-studio:latest
    ports:
      - "8081:8080"
    volumes:
      - label_studio_data:/label-studio/data
    networks:
      - saas_net

  # --- EMAIL SERVICE (Opcional, para enviar correos) ---
  mailpit:
      image: axllent/mailpit
      ports:
        - "8025:8025" # Interfaz web para ver emails
        - "1025:1025" # Puerto SMTP
      networks:
        - saas_net

networks:
  saas_net:
    driver: bridge

volumes:
  db_data:
  label_studio_data: